#!/bin/sh

argc=$#
author=$1
shift
_size=$1
shift
size=${_size:=5}
#echo $author, $size

svn log -v $@ | perl -e '
my $author=shift;
my $size=shift;
${n}=0; 
${flag}=0;
for(<>){
        if(/^r\d+.*?${author}.*?$/){
                #print "open flag", $_;
                ${flag}=1;
                ${n}++;
                if (${n} > ${size}) {
                        exit 0;
                }
        }
        if (${flag}) {
                print $_;
        }
        if(/^---+---$/){
                ${flag}=0;
                #print "close flag", $_;
        } 
}' $author $size
